# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

INPUT_PATH      = "vendor/qcom/features/"
CREATED_BY      = "centralized_featurization_tool"
DEFAULT_PROFILE = "default"
SCHEMA_FILE_PATH = "vendor/qcom/opensource/core-utils/centralized-features/features-control/docs/schema.yaml"
CENTRAL_YAML_HEADER = (
    "# =========================================================================== #\n"
    "# Centralized Feature YAML (AUTOGENERATED BY TOOL, READ-ONLY, DO NOT MODIFY). #\n"
    "# =========================================================================== #\n\n"
)

VARIANT_PATHS = {
    "qssi": {
        "yaml_out_dir":           "features-yaml/",
        "impl_gen_dir":           "features-impl-gen",
        "central_features_file":  "features-yaml/autogenerated-central.yaml",
        "snapshot_yaml_file":     "features-yaml/snapshot_central_yaml.yaml",
        "snapshot_artifact_file": "features-yaml/snapshot_generated_artifact.yaml",
    },
    "vendor": {
        "yaml_out_dir":           "features-vendor-yaml/",
        "impl_gen_dir":           "features-vendor-impl-gen",
        "central_features_file":  "features-vendor-yaml/autogenerated-central.yaml",
        "snapshot_yaml_file":     "features-vendor-yaml/snapshot_central_yaml.yaml",
        "snapshot_artifact_file": "features-vendor-yaml/snapshot_generated_artifact.yaml",
    },
}


def get_variant(target: str) -> str:
    """Return 'qssi' when target matches qssi*, else 'vendor'."""
    return "qssi" if target.startswith("qssi") else "vendor"

