# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Centralized Featurization Control Pre-process Tool - generator.py
# Generating build-time and runtime consumable artifacts for language‑specific features.
from common_utils import QtiFeatureUtils, QtiFeatureLogger, QtiFeatureConstants
from abc import ABC, abstractmethod
from typing import List
import os

# Interface class for all generators
class IGenerator(ABC):
    output_file = "" # output dir and file name

    def __init__(self):
        self.output_file_path_rel = ""  # relative path from project root to output file
        self.output_file_features_str = []  # generated feature definitions in string format
        self.output_file_values_str = []  # generated default value definitions in string format

    @abstractmethod
    def scope(self) -> str:
        '''
        Get the scope of IGenerator
        Returns:
            The scope
        '''

    def initiate(self, out_dir: str) -> int:
        '''
        Initialize the generator with the output directory
        Args:
            out_dir: Output directory path
        Returns:
            0 on success, -1 on failure
        '''
        try:
            self.output_file_path_rel = os.path.join(out_dir, self.output_file.lstrip("/"))
            output_dir = os.path.dirname(self.output_file_path_rel)
            if not os.path.isdir(output_dir):
                os.makedirs(output_dir, exist_ok=True)
            self.generate_header()
        except Exception as e:
            QtiFeatureLogger.error(f"Error creating folder {out_dir}: {e}")
            return -1
        return 0

    def generate_header(self) -> None:
        '''
        Generate header file content, usually consisting of some annotation information
        Invoked by initiate() function
        '''
        pass

    @abstractmethod
    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        '''
        Generate artifact for a specific feature node
        Args:
            feature_key: Feature key string
            feature_node: Feature node dictionary containing feature data
        Returns:
            0 on success, -1 on failure
        '''

    def generate_tail(self) -> None:
        '''
        Generate tail content, usually some end markers or cleanup works
        Invoked by complete() function
        '''
        pass

    def complete(self) -> int:
        # Finalize and write output file.
        try:
            self.generate_tail()
            QtiFeatureLogger.info(f"Writing file: {self.output_file_path_rel}")
            with open(self.output_file_path_rel, "w", encoding="utf-8") as file:
                file.write("".join(self.output_file_features_str))
                file.write("".join(self.output_file_values_str))
        except Exception as e:
            QtiFeatureLogger.error(f"Error writing file: {self.output_file_path_rel} error: {e}")
            return -1
        return 0

    def escape(self, feature_value: str) -> str:
        '''
        Escape special characters in feature value to make it suitable for usage
        Invoked by generate_artifact() function
        Args:
            feature_value: Feature value string to be escaped
        Returns:
            Escaped feature value string
        '''
        if feature_value is None:
            return '""'
        if len(feature_value) == 0:
            return '""'
        return "\"" + (feature_value.replace("\\", "\\\\")
                                    .replace('"', '\\"')) + "\""

# Makefile Generator Implementation
class MakeGenerator(IGenerator):
    # default output file path for make generator
    output_file = "/make_feature_config/config.mk"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_MAKE

    def generate_header(self) -> None:
        self.output_file_features_str.append("###--------this is auto generated by build engine, it is for GNU-Make based feature control, PLS do not manually modify it--------###\n\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        match feature_type:
            case QtiFeatureConstants.FEATURE_TYPE_BOOLEAN | QtiFeatureConstants.FEATURE_TYPE_INTEGER:
                self.output_file_features_str.append(f"{feature_key.upper()} := {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]).lower()}\n")
            case QtiFeatureConstants.FEATURE_TYPE_STRING:
                self.output_file_features_str.append(f"{feature_key.upper()} := {self.escape(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])}\n")
            case _:
                QtiFeatureLogger.info(f"generate artifact of scope {self.scope()}, key: {feature_key}, unsupported type: {feature_type}")
                return -1
        return 0

    def escape(self, feature_value: str) -> str:
        # Makefile variables don't use quoted strings; return bare value (unlike base class).
        if (feature_value is None):
            return ''
        if (len(feature_value) == 0):
            return ''
        return (feature_value.replace("\\", "\\\\")
                            .replace(" ", "\\ ")
                            .replace("$", "$$")
                            .replace("#", "\\#"))

# Native Generator Implementation
class NativeGenerator(IGenerator):
    # default output file path for native generator
    output_file = "/native_feature_query/qc_native_features.h"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_NATIVE

    def generate_header(self) -> None:
        self.output_file_features_str.append("/*--------this is auto generated by build engine, it is for native Feature/Default Value build config, PLS do not modify manually--------*/\n\n")
        self.output_file_features_str.append("#ifndef _QTI_CENTRAL_NATIVE_FEATURES_H_\n")
        self.output_file_features_str.append("#define _QTI_CENTRAL_NATIVE_FEATURES_H_\n")
        self.output_file_features_str.append("\n//Start Native Feature Definition\n")
        self.output_file_values_str.append("\n//Start Native Default Value Definition\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        match feature_type:
            case QtiFeatureConstants.FEATURE_TYPE_BOOLEAN:
                self.output_file_features_str.append(f"#define {feature_key.upper()} {str(int(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]))}\n")
            case QtiFeatureConstants.FEATURE_TYPE_INTEGER:
                self.output_file_values_str.append(f"#define {feature_key.upper()} {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])}\n")
            case QtiFeatureConstants.FEATURE_TYPE_STRING:
                self.output_file_values_str.append(f"#define {feature_key.upper()} {self.escape(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])}\n")
            case _:
                QtiFeatureLogger.info(f"generate artifact of scope {self.scope()}, key: {feature_key}, unsupported type: {feature_type}")
                return -1
        return 0

    def generate_tail(self) -> None:
        self.output_file_values_str.append("\n#endif // _QTI_CENTRAL_NATIVE_FEATURES_H_")

# Java Generator Implementation
class JavaGenerator(IGenerator):
    # default output file path for java generator
    output_file = "/java_feature_query/com/qualcomm/qti/plugin/feature_query/FeatureQuery.java"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_JAVA

    def generate_header(self) -> None:
        self.output_file_features_str.append("/*--------this is auto generated by build engine, it is for Java Feature build config, PLS do not modify manually--------*/\n\n")
        self.output_file_features_str.append("package com.qualcomm.qti.plugin.feature_query;\n\n")
        self.output_file_features_str.append("public final class FeatureQuery {\n")
        self.output_file_features_str.append("\n    /** Feature Configuration start*/\n")
        self.output_file_values_str.append("\n    /** Default Value Configuration start*/\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        match feature_type:
            case QtiFeatureConstants.FEATURE_TYPE_BOOLEAN:
                self.output_file_features_str.append(f"    public static final boolean {feature_key.upper()} = {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]).lower()};\n")
            case QtiFeatureConstants.FEATURE_TYPE_INTEGER:
                self.output_file_values_str.append(f"    public static final int {feature_key.upper()} = {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])};\n")
            case QtiFeatureConstants.FEATURE_TYPE_STRING:
                self.output_file_values_str.append(f"    public static final String {feature_key.upper()} = {self.escape(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])};\n")
            case _:
                QtiFeatureLogger.info(f"generate artifact of scope {self.scope()}, key: {feature_key}, unsupported type: {feature_type}")
                return -1
        return 0

    def generate_tail(self) -> None:
        self.output_file_values_str.append("\n}")

# Runtime native generator — emits cap_runtime_data.h consumed by the native
# capability query library.
class RuntimeNativeGenerator(IGenerator):
    output_file = "/soc_capability/native/cap_runtime_data.h"

    # Map YAML type strings to C CapDataType constants.
    _DTYPE_C = {
        QtiFeatureConstants.FEATURE_TYPE_BOOLEAN: "CAP_DTYPE_BOOL",
        QtiFeatureConstants.FEATURE_TYPE_INTEGER: "CAP_DTYPE_INT",
        QtiFeatureConstants.FEATURE_TYPE_STRING:  "CAP_DTYPE_STRING",
    }

    def __init__(self):
        super().__init__()
        # Tuples carry dtype: (key, val_str, dtype_str)
        self._default_entries: List[tuple] = []
        # dict values are (val_str, dtype_str)
        self._socid_override_dict: dict   = {}  # {(soc_id: int,  key: str): (val, dtype)}
        self._socname_override_dict: dict = {}  # {(soc_name: str, key: str): (val, dtype)}

    def scope(self) -> str:
        return QtiFeatureConstants.FEATURE_SCOPE_RUNTIME

    def _normalize(self, value, datatype: str) -> str:
        """Return the canonical string representation of a value for a given type."""
        if datatype == QtiFeatureConstants.FEATURE_TYPE_BOOLEAN:
            return "true" if value else "false"
        if datatype == QtiFeatureConstants.FEATURE_TYPE_INTEGER:
            return str(value)
        return str(value) if value is not None else ""

    def _emit_val(self, val: str, dtype_str: str) -> str:
        """Return a CapVal designated-initializer for the given value and dtype constant."""
        if dtype_str == "CAP_DTYPE_BOOL":
            return f'{{ .boolValue = {"true" if val == "true" else "false"} }}'
        if dtype_str == "CAP_DTYPE_INT":
            return f'{{ .intValue = {val} }}'
        return f'{{ .stringValue = "{self._escape(val)}" }}'

    def _dtype(self, datatype: str) -> str:
        return self._DTYPE_C.get(datatype, "CAP_DTYPE_STRING")

    def _escape(self, s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type  = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        feature_value = feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]
        key_upper     = feature_key.upper()
        dtype_str     = self._dtype(feature_type)

        self._default_entries.append((key_upper, self._normalize(feature_value, feature_type), dtype_str))

        for override in feature_node.get(QtiFeatureConstants.SOC_OVERRIDES_KEY, []):
            soc_ids   = override.get(QtiFeatureConstants.SOC_IDS_KEY, [])
            soc_names = override.get(QtiFeatureConstants.SOC_NAMES_KEY, [])
            val_str   = self._normalize(override.get(QtiFeatureConstants.SOC_OVERRIDE_VALUE_KEY), feature_type)

            for sid in soc_ids:
                self._socid_override_dict[(int(sid), key_upper)] = (val_str, dtype_str)

            for name in soc_names:
                self._socname_override_dict[(str(name).lower(), key_upper)] = (val_str, dtype_str)

        return 0

    def generate_header(self) -> None:
        a = self.output_file_features_str.append
        a("/*--------this is auto generated by build engine, it is for Runtime config, PLS do not modify manually--------*/\n\n")
        a("#ifndef _QTI_CAP_RUNTIME_DATA_H_\n")
        a("#define _QTI_CAP_RUNTIME_DATA_H_\n\n")
        a("#include <stdint.h>\n")
        a('#include "cap_runtime_api.h"\n\n')
        a("// Tagged value union — internal to the runtime library.\n")
        a("// Use the dataType field of each table entry to determine which member is valid.\n")
        a("typedef union {\n    bool        boolValue;\n    int         intValue;\n    const char* stringValue;\n} CapVal;\n\n")
        a("typedef struct {\n    const char* key;\n    CapVal      val;\n    CapDataType dataType;\n} CapKV;\n\n")
        a("typedef struct {\n    uint32_t    socId;\n    const char* key;\n    CapVal      val;\n    CapDataType dataType;\n} CapSocIdKV;\n\n")
        a("typedef struct {\n    const char* socName;\n    const char* key;\n    CapVal      val;\n    CapDataType dataType;\n} CapSocNameKV;\n\n")

    def generate_tail(self) -> None:
        self._default_entries.sort(key=lambda x: x[0])
        socid_overrides = sorted(
            [(sid, key, val, dtype) for (sid, key), (val, dtype) in self._socid_override_dict.items()],
            key=lambda x: (x[0], x[1])
        )
        socname_overrides = sorted(
            [(name, key, val, dtype) for (name, key), (val, dtype) in self._socname_override_dict.items()],
            key=lambda x: (x[0], x[1])
        )

        a = self.output_file_features_str.append

        # --- Default table ---
        if self._default_entries:
            a("static const CapKV kCapDefault[] = {\n")
            for key, val, dtype in self._default_entries:
                a(f'    {{ "{key}", {self._emit_val(val, dtype)}, {dtype} }},\n')
            a("};\n")
            a("#define CAP_DEFAULT_COUNT  ((int)(sizeof(kCapDefault) / sizeof(kCapDefault[0])))\n\n")
        else:
            a("static const CapKV* const kCapDefault = NULL;\n")
            a("#define CAP_DEFAULT_COUNT  0\n\n")

        b = self.output_file_values_str.append

        # --- soc_id override table ---
        if socid_overrides:
            b("static const CapSocIdKV kCapSocIdOverrides[] = {\n")
            for sid, key, val, dtype in socid_overrides:
                b(f'    {{ {sid}u, "{key}", {self._emit_val(val, dtype)}, {dtype} }},\n')
            b("};\n")
            b("#define CAP_SOCID_OVERRIDE_COUNT ((int)(sizeof(kCapSocIdOverrides) / sizeof(kCapSocIdOverrides[0])))\n\n")
        else:
            b("static const CapSocIdKV* const kCapSocIdOverrides = NULL;\n")
            b("#define CAP_SOCID_OVERRIDE_COUNT 0\n\n")

        # --- soc_name override table ---
        if socname_overrides:
            b("static const CapSocNameKV kCapSocNameOverrides[] = {\n")
            for name, key, val, dtype in socname_overrides:
                b(f'    {{ "{name}", "{key}", {self._emit_val(val, dtype)}, {dtype} }},\n')
            b("};\n")
            b("#define CAP_SOCNAME_OVERRIDE_COUNT ((int)(sizeof(kCapSocNameOverrides) / sizeof(kCapSocNameOverrides[0])))\n\n")
        else:
            b("static const CapSocNameKV* const kCapSocNameOverrides = NULL;\n")
            b("#define CAP_SOCNAME_OVERRIDE_COUNT 0\n\n")

        b("#endif /* _QTI_CAP_RUNTIME_DATA_H_ */\n")




# All Scope Generator Implementation
class AllScopeGenerator(IGenerator):
    def __init__(self, generators: List[IGenerator]):
        super().__init__()
        self.all_generators: List[IGenerator] = generators

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        for generator in self.all_generators:
            if generator.generate_artifact(feature_key, feature_node) != 0:
                return -1
        return 0

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_ALL

    def initiate(self, out_dir: str) -> int:
        # Each sub-generator manages its own output file; nothing to initialize here.
        return 0

    def complete(self) -> int:
        # Each sub-generator is completed individually via QtiFeatureGenerator.generate().
        return 0

class QtiFeatureGenerator:
    def __init__(self):
        self.registry = {} # map of generator name to generator instance

    def register_generators(self, out_dir: str, build_variant: str = "vendor") -> int:
        generators: List[IGenerator] = [
            MakeGenerator(),
            NativeGenerator(),
            JavaGenerator(),
        ]
        # Runtime artifact (cap_runtime_data.h) is only meaningful for the vendor
        # side.  The qssi/system side does not use the runtime capability query
        # lib, so skip generating that file.
        if build_variant != "qssi":
            generators.append(RuntimeNativeGenerator())
        else:
            QtiFeatureLogger.info("build_variant=qssi: skipping runtime artifact generation (cap_runtime_data.h)")

        all_scope_gen = AllScopeGenerator(generators)
        self.registry = {generator.scope(): generator for generator in generators}
        self.registry[QtiFeatureConstants.FEATURE_SCOPE_ALL] = all_scope_gen
        for scope, gen in self.registry.items():
            if gen.initiate(out_dir) != 0:
                return -1
        return 0

    # main entry point
    def generate(self, feature_dict: dict, out_dir: str, build_variant: str = "vendor") -> int:
        """
        INPUT :
        1. feature_dict # validated feature_dict by validator
        2. out_dir # the target directory where generated artifacts are written,
        it must be a stable, non-out/location so that generated artifacts survive clean builds and are available before Android build starts.
        3. build_variant # "vendor" (default) or "qssi"; qssi skips runtime artifact generation
        OUTPUT:
        1. artifacts written into stable, non-out/location
        2. return 0 if generate successfully, otherwise return -1
        """
        self.registry.clear()      # Clear any previous registry state
        if not feature_dict:
            QtiFeatureLogger.warning("Feature dictionary is empty, no artifacts will be generated")
            return 0

        QtiFeatureLogger.info("Registering generators...")
        if (self.register_generators(out_dir, build_variant) != 0):
            QtiFeatureLogger.error("Failed to register generators")
            return -1

        QtiFeatureLogger.info("Generating artifacts...")
        for feature_key, feature_node in QtiFeatureUtils.iter_feature_nodes(feature_dict):
            scope_list = feature_node[QtiFeatureConstants.FEATURE_SCOPE_KEY]
            if QtiFeatureConstants.FEATURE_SCOPE_ALL in scope_list:
                if self.registry[QtiFeatureConstants.FEATURE_SCOPE_ALL].generate_artifact(feature_key, feature_node) != 0:
                    QtiFeatureLogger.error(f"Feature '{feature_key}' failed for scope '{QtiFeatureConstants.FEATURE_SCOPE_ALL}'")
                    return -1
                continue
            for scope in dict.fromkeys(scope_list):
                if scope not in self.registry:
                    continue   # scope not registered (e.g. runtime skipped for qssi)
                if self.registry[scope].generate_artifact(feature_key, feature_node) != 0:
                    QtiFeatureLogger.error(f"Feature '{feature_key}' failed for scope '{scope}'")
                    return -1
        for scope in self.registry.keys():
            if (self.registry[scope].complete() != 0):
                return -1
        QtiFeatureLogger.info("Generating artifacts completed!!!")
        QtiFeatureLogger.info("The generator tool is completed!!!")
        return 0
