# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Centralized Featurization Control Pre-process Tool - generator.py
# Generating build-time and runtime consumable artifacts for language‑specific features.
from common_utils import QtiFeatureUtils, QtiFeatureLogger, QtiFeatureConstants
from abc import ABC, abstractmethod
from typing import List
import os

# Interface class for all generators
class IGenerator(ABC):
    output_file = "" # output dir and file name

    def __init__(self):
        self.output_file_path_rel = ""  # relative path from project root to output file
        self.output_file_features_str = []  # generated feature definitions in string format
        self.output_file_values_str = []  # generated default value definitions in string format

    @abstractmethod
    def scope(self) -> str:
        '''
        Get the scope of IGenerator
        Returns:
            The scope
        '''

    def initiate(self, out_dir: str) -> int:
        '''
        Initialize the generator with the output directory
        Args:
            out_dir: Output directory path
        Returns:
            0 on success, -1 on failure
        '''
        try:
            self.output_file_path_rel = os.path.join(out_dir, self.output_file.lstrip("/"))
            output_dir = os.path.dirname(self.output_file_path_rel)
            if not os.path.isdir(output_dir):
                os.makedirs(output_dir, exist_ok=True)
            self.generate_header()
        except Exception as e:
            QtiFeatureLogger.error(f"Error creating folder {out_dir}: {e}")
            return -1
        return 0

    def generate_header(self) -> None:
        '''
        Generate header file content, usually consisting of some annotation information
        Invoked by initiate() function
        '''
        pass

    @abstractmethod
    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        '''
        Generate artifact for a specific feature node
        Args:
            feature_key: Feature key string
            feature_node: Feature node dictionary containing feature data
        Returns:
            0 on success, -1 on failure
        '''

    def generate_tail(self) -> None:
        '''
        Generate tail content, usually some end markers or cleanup works
        Invoked by complete() function
        '''
        pass

    def complete(self) -> int:
        # Finalize and write output file.
        try:
            self.generate_tail()
            QtiFeatureLogger.info(f"Writing file: {self.output_file_path_rel}")
            with open(self.output_file_path_rel, "w", encoding="utf-8") as file:
                file.write("".join(self.output_file_features_str))
                file.write("".join(self.output_file_values_str))
        except Exception as e:
            QtiFeatureLogger.error(f"Error writing file: {self.output_file_path_rel} error: {e}")
            return -1
        return 0

    def escape(self, feature_value: str) -> str:
        '''
        Escape special characters in feature value to make it suitable for usage
        Invoked by generate_artifact() function
        Args:
            feature_value: Feature value string to be escaped
        Returns:
            Escaped feature value string
        '''
        if feature_value is None:
            return '""'
        if len(feature_value) == 0:
            return '""'
        return "\"" + (feature_value.replace("\\", "\\\\")
                                    .replace('"', '\\"')) + "\""

# Makefile Generator Implementation
class MakeGenerator(IGenerator):
    # default output file path for make generator
    output_file = "/make_feature_config/config.mk"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_MAKE

    def generate_header(self) -> None:
        self.output_file_features_str.append("###--------this is auto generated by build engine, it is for GNU-Make based feature control, PLS do not manually modify it--------###\n\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        match feature_type:
            case QtiFeatureConstants.FEATURE_TYPE_BOOLEAN | QtiFeatureConstants.FEATURE_TYPE_INTEGER:
                self.output_file_features_str.append(f"{feature_key.upper()} := {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]).lower()}\n")
            case QtiFeatureConstants.FEATURE_TYPE_STRING:
                self.output_file_features_str.append(f"{feature_key.upper()} := {self.escape(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])}\n")
            case _:
                QtiFeatureLogger.info(f"generate artifact of scope {self.scope()}, key: {feature_key}, unsupported type: {feature_type}")
                return -1
        return 0

    def escape(self, feature_value: str) -> str:
        # Makefile variables don't use quoted strings; return bare value (unlike base class).
        if (feature_value is None):
            return ''
        if (len(feature_value) == 0):
            return ''
        return (feature_value.replace("\\", "\\\\")
                            .replace(" ", "\\ ")
                            .replace("$", "$$")
                            .replace("#", "\\#"))

# Native Generator Implementation
class NativeGenerator(IGenerator):
    # default output file path for native generator
    output_file = "/native_feature_query/qc_native_features.h"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_NATIVE

    def generate_header(self) -> None:
        self.output_file_features_str.append("/*--------this is auto generated by build engine, it is for native Feature/Default Value build config, PLS do not modify manually--------*/\n\n")
        self.output_file_features_str.append("#ifndef _QTI_CENTRAL_NATIVE_FEATURES_H_\n")
        self.output_file_features_str.append("#define _QTI_CENTRAL_NATIVE_FEATURES_H_\n")
        self.output_file_features_str.append("\n//Start Native Feature Definition\n")
        self.output_file_values_str.append("\n//Start Native Default Value Definition\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        match feature_type:
            case QtiFeatureConstants.FEATURE_TYPE_BOOLEAN:
                self.output_file_features_str.append(f"#define {feature_key.upper()} {str(int(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]))}\n")
            case QtiFeatureConstants.FEATURE_TYPE_INTEGER:
                self.output_file_values_str.append(f"#define {feature_key.upper()} {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])}\n")
            case QtiFeatureConstants.FEATURE_TYPE_STRING:
                self.output_file_values_str.append(f"#define {feature_key.upper()} {self.escape(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])}\n")
            case _:
                QtiFeatureLogger.info(f"generate artifact of scope {self.scope()}, key: {feature_key}, unsupported type: {feature_type}")
                return -1
        return 0

    def generate_tail(self) -> None:
        self.output_file_values_str.append("\n#endif // _QTI_CENTRAL_NATIVE_FEATURES_H_")

# Java Generator Implementation
class JavaGenerator(IGenerator):
    # default output file path for java generator
    output_file = "/java_feature_query/com/qualcomm/qti/plugin/feature_query/FeatureQuery.java"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_JAVA

    def generate_header(self) -> None:
        self.output_file_features_str.append("/*--------this is auto generated by build engine, it is for Java Feature build config, PLS do not modify manually--------*/\n\n")
        self.output_file_features_str.append("package com.qualcomm.qti.plugin.feature_query;\n\n")
        self.output_file_features_str.append("public final class FeatureQuery {\n")
        self.output_file_features_str.append("\n    /** Feature Configuration start*/\n")
        self.output_file_values_str.append("\n    /** Default Value Configuration start*/\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        feature_type = feature_node[QtiFeatureConstants.FEATURE_TYPE_KEY]
        match feature_type:
            case QtiFeatureConstants.FEATURE_TYPE_BOOLEAN:
                self.output_file_features_str.append(f"    public static final boolean {feature_key.upper()} = {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY]).lower()};\n")
            case QtiFeatureConstants.FEATURE_TYPE_INTEGER:
                self.output_file_values_str.append(f"    public static final int {feature_key.upper()} = {str(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])};\n")
            case QtiFeatureConstants.FEATURE_TYPE_STRING:
                self.output_file_values_str.append(f"    public static final String {feature_key.upper()} = {self.escape(feature_node[QtiFeatureConstants.FEATURE_VALUE_KEY])};\n")
            case _:
                QtiFeatureLogger.info(f"generate artifact of scope {self.scope()}, key: {feature_key}, unsupported type: {feature_type}")
                return -1
        return 0

    def generate_tail(self) -> None:
        self.output_file_values_str.append("\n}")

# soc runtime generator implementation
class RuntimeGenerator(IGenerator):
    # default output file path for runtime generator
    output_file = "/soc_capability/native/cap_runtime_data.h"

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_RUNTIME

    def generate_header(self) -> None:
        self.output_file_features_str.append("/*--------this is auto generated by build engine, it is for Runtime config, PLS do not modify manually--------*/\n")

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        return 0

# All Scope Generator Implementation
class AllScopeGenerator(IGenerator):
    def __init__(self, generators: List[IGenerator]):
        super().__init__()
        self.all_generators: List[IGenerator] = generators

    def generate_artifact(self, feature_key: str, feature_node: dict) -> int:
        for generator in self.all_generators:
            if generator.generate_artifact(feature_key, feature_node) != 0:
                return -1
        return 0

    def scope(self):
        return QtiFeatureConstants.FEATURE_SCOPE_ALL

    def initiate(self, out_dir: str) -> int:
        # Each sub-generator manages its own output file; nothing to initialize here.
        return 0

    def complete(self) -> int:
        # Each sub-generator is completed individually via QtiFeatureGenerator.generate().
        return 0

class QtiFeatureGenerator:
    def __init__(self):
        self.registry = {} # map of generator name to generator instance

    def register_generators(self, out_dir:str) -> int:
        generators: List[IGenerator] = [
                MakeGenerator(),
                NativeGenerator(),
                JavaGenerator(),
                RuntimeGenerator()
            ]
        all_scope_gen = AllScopeGenerator(generators)
        self.registry = {generator.scope(): generator for generator in generators}
        self.registry[QtiFeatureConstants.FEATURE_SCOPE_ALL] = all_scope_gen
        for scope, gen in self.registry.items():
            if gen.initiate(out_dir) != 0:
                return -1
        return 0

    # main entry point
    def generate(self, feature_dict: dict, out_dir: str) -> int:
        """
        INPUT :
        1. feature_dict # validated feature_dict by validator
        2. out_dir # the target directory where generated artifacts are written,
        it must be a stable, non-out/location so that generated artifacts survive clean builds and are available before Android build starts.
        OUTPUT:
        1. artifacts written into stable, non-out/location
        2. return 0 if generate successfully, otherwise return -1
        """
        self.registry.clear()      # Clear any previous registry state
        if not feature_dict:
            QtiFeatureLogger.warning("Feature dictionary is empty, no artifacts will be generated")
            return 0

        QtiFeatureLogger.info("Registering generators...")
        if (self.register_generators(out_dir) != 0):
            QtiFeatureLogger.error("Failed to register generators")
            return -1

        QtiFeatureLogger.info("Generating artifacts...")
        for feature_key, feature_node in QtiFeatureUtils.iter_feature_nodes(feature_dict):
            scope_list = feature_node[QtiFeatureConstants.FEATURE_SCOPE_KEY]
            if QtiFeatureConstants.FEATURE_SCOPE_ALL in scope_list:
                if self.registry[QtiFeatureConstants.FEATURE_SCOPE_ALL].generate_artifact(feature_key, feature_node) != 0:
                    QtiFeatureLogger.error(f"Feature '{feature_key}' failed for scope '{QtiFeatureConstants.FEATURE_SCOPE_ALL}'")
                    return -1
                continue
            for scope in dict.fromkeys(scope_list):
                if self.registry[scope].generate_artifact(feature_key, feature_node) != 0:
                    QtiFeatureLogger.error(f"Feature '{feature_key}' failed for scope '{scope}'")
                    return -1
        for scope in self.registry.keys():
            if (self.registry[scope].complete() != 0):
                return -1
        QtiFeatureLogger.info("Generating artifacts completed!!!")
        QtiFeatureLogger.info("The generator tool is completed!!!")
        return 0