# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

#!/usr/bin/python
import os
import sys
from argparse import ArgumentParser
from pathlib import Path
from stitch_parser import parse_and_stitch, dump_centralized_file
import central_feature_tool_constants as constants
from incremental_build import incremental_build, dump_hash, save_artifact_snapshot
from validator import QtiFeatureValidator
from generator import QtiFeatureGenerator
from common_utils import QtiFeatureLogger
from build_types import BuildConfig, BuildPaths, BuildStatus

logger = QtiFeatureLogger()


def parser_config() -> ArgumentParser:
    parser = ArgumentParser()
    parser.add_argument("--input_path", type=str, default=constants.INPUT_PATH)
    parser.add_argument("--out_dir", type=str, required=True)
    parser.add_argument("--schema", type=str, default=None)
    parser.add_argument("--profile", type=str, default=constants.DEFAULT_PROFILE)
    parser.add_argument("--target", type=str, required=True)
    parser.add_argument("--params", default={})
    return parser


def resolve_yaml_files(config: BuildConfig) -> list[str]:
    """
    INPUT:
        config: BuildConfig with input_path, profile, target
    OUTPUT:
        List of resolved YAML file paths, or empty list on error.
    """
    yaml_file_path = f"*/{config.profile}/{config.target}/*.yaml"
    resolved = []
    if not os.path.exists(config.input_path):
        logger.error(f"[main]: input yaml fragment path {config.input_path} does not exist")
        return resolved
    root = Path(config.input_path)
    resolved.extend(str(f) for f in root.rglob(yaml_file_path))
    return resolved


def run(config: BuildConfig, paths: BuildPaths) -> int:
    """
    INPUT:
        config: build identity and input configuration
        paths:  all output/intermediate file paths
    OUTPUT:
        0:  pipeline completed successfully.
        -1: pipeline failed.
    """
    logger.info("[main]: Starting...")
    logger.info("[main]: Resolving yaml files")
    yaml_files = resolve_yaml_files(config)
    if not yaml_files:
        logger.warning(f"[main]: No YAML files resolved for target: {config.target} and profile: {config.profile}")
        # logger.info("[main]: Skipping build")
        # return 0
    logger.info("[main]: Resolved yaml files")

    logger.info("[main]: Stitching and parsing yaml files")
    ret, stitch = parse_and_stitch(yaml_files, config, paths.yaml_out_dir)
    if ret != 0:
        logger.error(f"[main]: stitch & parse failed for target: {config.target} and profile: {config.profile}")
        return -1
    logger.info("[main]: Stitching and parsing successful")

    validator = QtiFeatureValidator()
    ret = validator.validate(stitch.feature_dict, stitch.schema_dict)
    if ret != 0:
        logger.error(f"[main]: validation failed for target: {config.target} and profile: {config.profile}")
        return -1
    logger.info("[main]: validation successful")

    generator = QtiFeatureGenerator()
    ret = generator.generate(stitch.feature_dict, paths.gen_out_dir, build_variant=config.build_variant)
    if ret != 0:
        logger.error(f"[main]: generator failed for target: {config.target} and profile: {config.profile}")
        return -1
    logger.info("[main]: generator successful")

    ret = dump_centralized_file(stitch.combined_content, paths.central_yaml)
    if ret != 0:
        logger.error(f"[main]: saving autogenerated central yaml failed for target: {config.target} and profile: {config.profile}")
        return -1

    ret = dump_hash(stitch.combined_content, paths.snapshot_yaml)
    if ret != 0:
        logger.error(f"[main]: saving central file metadata failed for target: {config.target} and profile: {config.profile}")
        return -1

    ret = save_artifact_snapshot(paths)
    if ret != 0:
        logger.error(f"[main]: saving artifact metadata failed for target: {config.target} and profile: {config.profile}")
        return -1

    logger.info("[main] build complete")
    return 0


def main() -> int:
    parser = parser_config()
    args = parser.parse_args()

    build_variant = constants.get_variant(args.target)
    schema = args.schema or constants.SCHEMA_FILE_PATH

    config = BuildConfig(
        input_path=args.input_path,
        out_dir=args.out_dir,
        schema_config_path=schema,
        profile=args.profile,
        target=args.target,
        build_variant=build_variant,
        extra_params=args.params,
    )
    paths = BuildPaths(out_dir=args.out_dir, build_variant=build_variant)


    yaml_files_list = resolve_yaml_files(config)
    ret, status = incremental_build(yaml_files_list, config, paths)
    if ret != 0:
        logger.error("[main] error in incremental build.")
        logger.error("[main] build aborted")
        return -1
    if status == BuildStatus.FULL_RUN:
        return run(config, paths)
    if status == BuildStatus.NO_CHANGE:
        logger.info("[main] No change detected. Skipping build.")
        return 0
    logger.error("[main] unknown error.")
    return -1


if __name__ == '__main__':
    sys.exit(main())
